name: morpheus-graphql-cli
version: 0.1.0
github: "https://github.com/morpheusgraphql/morpheus-graphql-cli"
license: BSD3
author: "Daviti Nalchevanidze"
category: web, graphql, cli
synopsis: Morpheus GraphQL CLI
maintainer: "d.nalchevanidze@gmail.com"
homepage: https://morpheusgraphql.com
copyright: "(c) 2019 Daviti Nalchevanidze"

description: code generator for Morpheus GraphQL

extra-source-files:
  - changelog.md
  - README.md

dependencies:
  - base                  >= 4.7       && <  5
  - morpheus-graphql      >= 0.6.2
  - bytestring
  - optparse-applicative  >= 0.12      && <  0.15
  - filepath              >= 1.1       && <  1.5
  - text                  >= 1.2.3.0   && <  1.3
  - bytestring            >= 0.10.4    && <  0.11
#  - containers            >= 0.4.2.1   && <  0.7
#  - unordered-containers  >= 0.2.8.0   && <  0.3
#  - transformers          >= 0.3.0.0   && <  0.6
#  - scientific            >= 0.3.6.2   && <  0.4
#  - vector                >= 0.12.0.1  && <  0.13
#  - mtl                   >= 2.0       && <= 2.3
#  - aeson                 >= 1.4.4.0   && <= 1.6

tests:
  morpheus-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall

executables:
  morpheus:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
